profile-name : beta

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    # url: jdbc:mysql://211.45.170.92:3306/board?useSSL=false&allowPublicKeyRetrieval=true
    # # url: jdbc:mysql://board-project-db.cultylr0esxi.ap-northeast-2.rds.amazonaws.com:3306/board
    # username: brand13
    # password: kind0314
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:~/test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    database: mysql
    # database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create #data.sql? ????? ???.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        dialect.storage_engine: innodb
        format_sql: true
        default_batch_fetch_size: 100 # 최대 100개의 bulk로 select
        show_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
  h2:
    console:
      enabled: true
  # sql:
  #   init:
  #     mode: always # data.sql ??? ?? ??? ???(embeded: ??????.. Always: ???)
  output:   # spring.output.ansi.enabled=ALWAYS 로그 색상 추가 
    ansi:
      enabled: ALWAYS 